templates:
  tmdb:
    optional:
      - collection
      - movie
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

collections:
  The Lord of the Rings:
    template: {name: tmdb, collection: 119}
    name_mapping: Lord of the Rings
    item_label: LOTR,Middle Earth
