templates:
  tmdb:
    optional:
      - collection
      - movie
      - company
      - tmdb_summary
      - summary
      - order
    tmdb_collection_details: <<collection>>
    tmdb_movie: <<movie>>
    tmdb_company: <<company>>
    tmdb_summary: <<tmdb_summary>>
    summary: <<summary>>
    sync_mode: sync
    collection_order: release
    move_prefix: The,A

#
# CURATED COLLECTIONS
# Curated -- either not official TMDB collections, or specific combinations of movies
#

collections:

  "Horror Block Short Film Festival 2015":
    template:
      name: tmdb
      movie: 
        - 727111
        - 727128
        - 727129
        - 727136
        - 260795
    collection_order: alpha
    collection_mode: show_items

  "Nightmare Movies":
    template:
      name: tmdb
      movie: 
        - 36599 # Prom Night
        - 39929 # Prom Night II
        - 132935 # Blind Witness
        - 138858 # Dire Wolf
        - 38500 # Howling IV
        - 128643 # KillerKiller
        - 27711 # Killjoy
        - 39050 # Meadowoods
        - 318666 # Occupied
        - 222621 # Samuel Bleak
        - 42663 # The Cry
        - 40877 # The Familiar
        - 274081 # The Inflicted
        - 83323 # The Nurse
        - 106028 # Summer School
    summary: "You'll never sleep again!"
    collection_order: alpha
    collection_mode: show_items
